import type { GroceryCategory } from "@/lib/types"

// Lowercase keyword → category
// Checked via substring match, so "tomato" matches "cherry tomatoes"
const KEYWORD_MAP: [string, GroceryCategory][] = [
  // Fruits & Vegetables
  ["sweet potato", "Fruits & Vegetables"],
  ["sötpotatis", "Fruits & Vegetables"],
  ["cherry tomato", "Fruits & Vegetables"],
  ["körsbärstomat", "Fruits & Vegetables"],
  ["brussels sprout", "Fruits & Vegetables"],
  ["brysselkål", "Fruits & Vegetables"],
  ["cauliflower", "Fruits & Vegetables"],
  ["blomkål", "Fruits & Vegetables"],
  ["pomegranate", "Fruits & Vegetables"],
  ["granatäpple", "Fruits & Vegetables"],
  ["eggplant", "Fruits & Vegetables"],
  ["aubergine", "Fruits & Vegetables"],
  ["sugar snaps", "Fruits & Vegetables"],
  ["sockerärtor", "Fruits & Vegetables"],
  ["bell pepper", "Fruits & Vegetables"],
  ["haricots verts", "Fruits & Vegetables"],
  ["green beans", "Fruits & Vegetables"],
  ["gröna bönor", "Fruits & Vegetables"],
  ["asparagus", "Fruits & Vegetables"],
  ["sparris", "Fruits & Vegetables"],
  ["artichoke", "Fruits & Vegetables"],
  ["ärtskocka", "Fruits & Vegetables"],
  ["watermelon", "Fruits & Vegetables"],
  ["vattenmelon", "Fruits & Vegetables"],
  ["blueberries", "Fruits & Vegetables"],
  ["blåbär", "Fruits & Vegetables"],
  ["raspberries", "Fruits & Vegetables"],
  ["hallon", "Fruits & Vegetables"],
  ["strawberries", "Fruits & Vegetables"],
  ["jordgubbar", "Fruits & Vegetables"],
  ["blackberry", "Fruits & Vegetables"],
  ["björnbär", "Fruits & Vegetables"],
  ["cranberry", "Fruits & Vegetables"],
  ["tranbär", "Fruits & Vegetables"],
  ["pineapple", "Fruits & Vegetables"],
  ["ananas", "Fruits & Vegetables"],
  ["nectarine", "Fruits & Vegetables"],
  ["nektarin", "Fruits & Vegetables"],
  ["apricot", "Fruits & Vegetables"],
  ["aprikos", "Fruits & Vegetables"],
  ["grapefruit", "Fruits & Vegetables"],
  ["blodapelsin", "Fruits & Vegetables"],
  ["mandarin", "Fruits & Vegetables"],
  ["clementine", "Fruits & Vegetables"],
  ["klementin", "Fruits & Vegetables"],
  ["parsnip", "Fruits & Vegetables"],
  ["palsternacka", "Fruits & Vegetables"],
  ["beetroot", "Fruits & Vegetables"],
  ["rödbeta", "Fruits & Vegetables"],
  ["radish", "Fruits & Vegetables"],
  ["rädisa", "Fruits & Vegetables"],
  ["cabbage", "Fruits & Vegetables"],
  ["vitkål", "Fruits & Vegetables"],
  ["red cabbage", "Fruits & Vegetables"],
  ["rödkål", "Fruits & Vegetables"],
  ["kale", "Fruits & Vegetables"],
  ["grönkål", "Fruits & Vegetables"],
  ["leek", "Fruits & Vegetables"],
  ["purjolök", "Fruits & Vegetables"],
  ["spring onion", "Fruits & Vegetables"],
  ["salladslök", "Fruits & Vegetables"],
  ["shallot", "Fruits & Vegetables"],
  ["schalottenlök", "Fruits & Vegetables"],
  ["rhubarb", "Fruits & Vegetables"],
  ["rabarber", "Fruits & Vegetables"],
  ["spinach", "Fruits & Vegetables"],
  ["spenat", "Fruits & Vegetables"],
  ["arugula", "Fruits & Vegetables"],
  ["ruccola", "Fruits & Vegetables"],
  ["bok choy", "Fruits & Vegetables"],
  ["broccoli", "Fruits & Vegetables"],
  ["zucchini", "Fruits & Vegetables"],
  ["squash", "Fruits & Vegetables"],
  ["cucumber", "Fruits & Vegetables"],
  ["gurka", "Fruits & Vegetables"],
  ["carrot", "Fruits & Vegetables"],
  ["morot", "Fruits & Vegetables"],
  ["potato", "Fruits & Vegetables"],
  ["potatis", "Fruits & Vegetables"],
  ["tomato", "Fruits & Vegetables"],
  ["tomat", "Fruits & Vegetables"],
  ["onion", "Fruits & Vegetables"],
  ["lök", "Fruits & Vegetables"],
  ["apple", "Fruits & Vegetables"],
  ["äpple", "Fruits & Vegetables"],
  ["banana", "Fruits & Vegetables"],
  ["banan", "Fruits & Vegetables"],
  ["garlic", "Fruits & Vegetables"],
  ["vitlök", "Fruits & Vegetables"],
  ["lemon", "Fruits & Vegetables"],
  ["citron", "Fruits & Vegetables"],
  ["lime", "Fruits & Vegetables"],
  ["orange", "Fruits & Vegetables"],
  ["apelsin", "Fruits & Vegetables"],
  ["pear", "Fruits & Vegetables"],
  ["päron", "Fruits & Vegetables"],
  ["grape", "Fruits & Vegetables"],
  ["druva", "Fruits & Vegetables"],
  ["melon", "Fruits & Vegetables"],
  ["mango", "Fruits & Vegetables"],
  ["kiwi", "Fruits & Vegetables"],
  ["plum", "Fruits & Vegetables"],
  ["plommon", "Fruits & Vegetables"],
  ["peach", "Fruits & Vegetables"],
  ["persika", "Fruits & Vegetables"],
  ["ginger", "Fruits & Vegetables"],
  ["ingefära", "Fruits & Vegetables"],
  ["celery", "Fruits & Vegetables"],
  ["selleri", "Fruits & Vegetables"],
  ["mushroom", "Fruits & Vegetables"],
  ["svamp", "Fruits & Vegetables"],
  ["champinjon", "Fruits & Vegetables"],
  ["kantarell", "Fruits & Vegetables"],
  ["herbs", "Fruits & Vegetables"],
  ["örtsalt", "Spices & Seasonings"], // Exception for salt
  ["örter", "Fruits & Vegetables"],
  ["parsley", "Fruits & Vegetables"],
  ["persilja", "Fruits & Vegetables"],
  ["cilantro", "Fruits & Vegetables"],
  ["coriander", "Fruits & Vegetables"],
  ["koriander", "Fruits & Vegetables"],
  ["dill", "Fruits & Vegetables"],
  ["chives", "Fruits & Vegetables"],
  ["gräslök", "Fruits & Vegetables"],

  // Meat & Seafood
  ["chicken breast", "Meat & Seafood"],
  ["kycklingfilé", "Meat & Seafood"],
  ["chicken wings", "Meat & Seafood"],
  ["kycklingvingar", "Meat & Seafood"],
  ["pork belly", "Meat & Seafood"],
  ["sidfläsk", "Meat & Seafood"],
  ["pork loin", "Meat & Seafood"],
  ["fläskytterfilé", "Meat & Seafood"],
  ["beef tenderloin", "Meat & Seafood"],
  ["oxfilé", "Meat & Seafood"],
  ["entrecote", "Meat & Seafood"],
  ["ribeye", "Meat & Seafood"],
  ["sirloin", "Meat & Seafood"],
  ["ryggbiff", "Meat & Seafood"],
  ["ground beef", "Meat & Seafood"],
  ["nötfärs", "Meat & Seafood"],
  ["ground pork", "Meat & Seafood"],
  ["fläskfärs", "Meat & Seafood"],
  ["meatballs", "Meat & Seafood"],
  ["köttbullar", "Meat & Seafood"],
  ["lamb chops", "Meat & Seafood"],
  ["lammracks", "Meat & Seafood"],
  ["chorizo", "Meat & Seafood"],
  ["salami", "Meat & Seafood"],
  ["prosciutto", "Meat & Seafood"],
  ["parmaskinka", "Meat & Seafood"],
  ["ham", "Meat & Seafood"],
  ["skinka", "Meat & Seafood"],
  ["turkey", "Meat & Seafood"],
  ["kalkon", "Meat & Seafood"],
  ["bacon", "Meat & Seafood"],
  ["sausage", "Meat & Seafood"],
  ["korv", "Meat & Seafood"],
  ["bratwurst", "Meat & Seafood"],
  ["falukorv", "Meat & Seafood"],
  ["salmon", "Meat & Seafood"],
  ["lax", "Meat & Seafood"],
  ["cod", "Meat & Seafood"],
  ["torsk", "Meat & Seafood"],
  ["mackerel", "Meat & Seafood"],
  ["makrill", "Meat & Seafood"],
  ["herring", "Meat & Seafood"],
  ["sill", "Meat & Seafood"],
  ["tuna", "Meat & Seafood"],
  ["tonfisk", "Meat & Seafood"],
  ["shrimp", "Meat & Seafood"],
  ["räkor", "Meat & Seafood"],
  ["prawns", "Meat & Seafood"],
  ["lobster", "Meat & Seafood"],
  ["hummer", "Meat & Seafood"],
  ["crab", "Meat & Seafood"],
  ["krabba", "Meat & Seafood"],
  ["mussels", "Meat & Seafood"],
  ["musslor", "Meat & Seafood"],
  ["scallops", "Meat & Seafood"],
  ["pilgrimsmusslor", "Meat & Seafood"],
  ["mince", "Meat & Seafood"],
  ["färs", "Meat & Seafood"],
  ["steak", "Meat & Seafood"],
  ["meat", "Meat & Seafood"],
  ["kött", "Meat & Seafood"],

  // Dairy & Eggs
  ["oat milk", "Dairy & Eggs"], // Usually found in dairy aisle
  ["havremjölk", "Dairy & Eggs"],
  ["soy milk", "Dairy & Eggs"],
  ["sojamjölk", "Dairy & Eggs"],
  ["almond milk", "Dairy & Eggs"],
  ["mandeldryck", "Dairy & Eggs"],
  ["whipping cream", "Dairy & Eggs"],
  ["vispgrädde", "Dairy & Eggs"],
  ["sour cream", "Dairy & Eggs"],
  ["gräddfil", "Dairy & Eggs"],
  ["crème fraiche", "Dairy & Eggs"],
  ["créme fraiche", "Dairy & Eggs"],
  ["cottage cheese", "Dairy & Eggs"],
  ["keso", "Dairy & Eggs"],
  ["cream cheese", "Dairy & Eggs"],
  ["färskost", "Dairy & Eggs"],
  ["brie", "Dairy & Eggs"],
  ["camembert", "Dairy & Eggs"],
  ["gorgonzola", "Dairy & Eggs"],
  ["parmesan", "Dairy & Eggs"],
  ["halloumi", "Dairy & Eggs"],
  ["paneer", "Dairy & Eggs"],
  ["mozzarella", "Dairy & Eggs"],
  ["feta", "Dairy & Eggs"],
  ["greek yogurt", "Dairy & Eggs"],
  ["grekisk yoghurt", "Dairy & Eggs"],
  ["filfil", "Dairy & Eggs"],
  ["filmjölk", "Dairy & Eggs"],
  ["margarine", "Dairy & Eggs"],
  ["margarin", "Dairy & Eggs"],
  ["butter", "Dairy & Eggs"],
  ["smör", "Dairy & Eggs"],
  ["milk", "Dairy & Eggs"],
  ["mjölk", "Dairy & Eggs"],
  ["cheese", "Dairy & Eggs"],
  ["ost", "Dairy & Eggs"],
  ["yogurt", "Dairy & Eggs"],
  ["yoghurt", "Dairy & Eggs"],
  ["cream", "Dairy & Eggs"],
  ["grädde", "Dairy & Eggs"],
  ["egg", "Dairy & Eggs"],
  ["ägg", "Dairy & Eggs"],
  ["kvarg", "Dairy & Eggs"],
  ["quark", "Dairy & Eggs"],

  // Bakery
  ["sourdough", "Bakery"],
  ["surdeg", "Bakery"],
  ["whole grain bread", "Bakery"],
  ["fullkornsbröd", "Bakery"],
  ["rye bread", "Bakery"],
  ["rågbröd", "Bakery"],
  ["knäckebröd", "Bakery"],
  ["crispbread", "Bakery"],
  ["flatbread", "Bakery"],
  ["tunnbröd", "Bakery"],
  ["hamburger bun", "Bakery"],
  ["hamburgerbröd", "Bakery"],
  ["hot dog bun", "Bakery"],
  ["korvbröd", "Bakery"],
  ["baguette", "Bakery"],
  ["ciabatta", "Bakery"],
  ["focaccia", "Bakery"],
  ["muffin", "Bakery"],
  ["donut", "Bakery"],
  ["munk", "Bakery"],
  ["cookie", "Bakery"],
  ["kaka", "Bakery"],
  ["biscuit", "Bakery"],
  ["kex", "Bakery"],
  ["cinnamon bun", "Bakery"],
  ["kanelbulle", "Bakery"],
  ["bread", "Bakery"],
  ["bröd", "Bakery"],
  ["bagel", "Bakery"],
  ["croissant", "Bakery"],
  ["tortilla", "Bakery"],
  ["bun", "Bakery"],
  ["bulle", "Bakery"],
  ["cake", "Bakery"],
  ["tårta", "Bakery"],
  ["pastry", "Bakery"],
  ["bakelse", "Bakery"],

  // Frozen
  ["frozen vegetables", "Frozen"],
  ["frysta grönsaker", "Frozen"],
  ["frozen fruit", "Frozen"],
  ["fryst frukt", "Frozen"],
  ["frozen pizza", "Frozen"],
  ["fryspizza", "Frozen"],
  ["ice cream", "Frozen"],
  ["glass", "Frozen"],
  ["sorbet", "Frozen"],
  ["popsicles", "Frozen"],
  ["ispinnar", "Frozen"],
  ["frozen berries", "Frozen"],
  ["frysta bär", "Frozen"],
  ["frozen", "Frozen"],
  ["fryst", "Frozen"],

  // Canned & Jarred
  ["peanut butter", "Condiments & Sauces"],
  ["nötssmör", "Condiments & Sauces"],
  ["canned tomatoes", "Canned & Jarred"],
  ["konserverade tomater", "Canned & Jarred"],
  ["crushed tomatoes", "Canned & Jarred"],
  ["krossade tomater", "Canned & Jarred"],
  ["tomato paste", "Canned & Jarred"],
  ["tomatpuré", "Canned & Jarred"],
  ["coconut milk", "Canned & Jarred"],
  ["kokosmjölk", "Canned & Jarred"],
  ["chickpeas", "Canned & Jarred"],
  ["kikärtor", "Canned & Jarred"],
  ["kidney beans", "Canned & Jarred"],
  ["kidneybönor", "Canned & Jarred"],
  ["black beans", "Canned & Jarred"],
  ["svarta bönor", "Canned & Jarred"],
  ["lentils", "Canned & Jarred"],
  ["linser", "Canned & Jarred"],
  ["corn", "Canned & Jarred"],
  ["majs", "Canned & Jarred"],
  ["olives", "Canned & Jarred"],
  ["oliver", "Canned & Jarred"],
  ["capers", "Canned & Jarred"],
  ["kapris", "Canned & Jarred"],
  ["pickles", "Canned & Jarred"],
  ["saltgurka", "Canned & Jarred"],
  ["smörgåsgurka", "Canned & Jarred"],
  ["jalapenos", "Canned & Jarred"],
  ["sundried tomatoes", "Canned & Jarred"],
  ["soltorkade tomater", "Canned & Jarred"],
  ["pesto", "Canned & Jarred"],
  ["tuna in oil", "Canned & Jarred"],
  ["canned", "Canned & Jarred"],
  ["konserv", "Canned & Jarred"],
  ["beans", "Canned & Jarred"],
  ["bönor", "Canned & Jarred"],

  // Grains & Pasta
  ["spaghetti", "Grains & Pasta"],
  ["macaroni", "Grains & Pasta"],
  ["makaroner", "Grains & Pasta"],
  ["fusilli", "Grains & Pasta"],
  ["penne", "Grains & Pasta"],
  ["lasagna", "Grains & Pasta"],
  ["basmati rice", "Grains & Pasta"],
  ["jasmine rice", "Grains & Pasta"],
  ["jasminris", "Grains & Pasta"],
  ["brown rice", "Grains & Pasta"],
  ["råris", "Grains & Pasta"],
  ["oatmeal", "Grains & Pasta"],
  ["havregryn", "Grains & Pasta"],
  ["muesli", "Grains & Pasta"],
  ["müsli", "Grains & Pasta"],
  ["granola", "Grains & Pasta"],
  ["wheat flour", "Grains & Pasta"],
  ["vetemjöl", "Grains & Pasta"],
  ["rye flour", "Grains & Pasta"],
  ["rågmjöl", "Grains & Pasta"],
  ["baking powder", "Grains & Pasta"],
  ["bakpulver", "Grains & Pasta"],
  ["yeast", "Grains & Pasta"],
  ["jäst", "Grains & Pasta"],
  ["sugar", "Grains & Pasta"],
  ["socker", "Grains & Pasta"],
  ["brown sugar", "Grains & Pasta"],
  ["farinsocker", "Grains & Pasta"],
  ["pasta", "Grains & Pasta"],
  ["rice", "Grains & Pasta"],
  ["ris", "Grains & Pasta"],
  ["noodle", "Grains & Pasta"],
  ["nudel", "Grains & Pasta"],
  ["oat", "Grains & Pasta"],
  ["havre", "Grains & Pasta"],
  ["flour", "Grains & Pasta"],
  ["mjöl", "Grains & Pasta"],
  ["cereal", "Grains & Pasta"],
  ["flingor", "Grains & Pasta"],
  ["couscous", "Grains & Pasta"],
  ["quinoa", "Grains & Pasta"],
  ["bulgur", "Grains & Pasta"],

  // Snacks
  ["potato chips", "Snacks"],
  ["potatischips", "Snacks"],
  ["tortilla chips", "Snacks"],
  ["cheese puffs", "Snacks"],
  ["ostbågar", "Snacks"],
  ["popcorn", "Snacks"],
  ["peanuts", "Snacks"],
  ["jordnötter", "Snacks"],
  ["cashews", "Snacks"],
  ["walnuts", "Snacks"],
  ["valnötter", "Snacks"],
  ["almonds", "Snacks"],
  ["mandlar", "Snacks"],
  ["dark chocolate", "Snacks"],
  ["mörk choklad", "Snacks"],
  ["milk chocolate", "Snacks"],
  ["mjölkchoklad", "Snacks"],
  ["gummy bears", "Snacks"],
  ["geléhallon", "Snacks"],
  ["licorice", "Snacks"],
  ["lakrits", "Snacks"],
  ["chips", "Snacks"],
  ["nuts", "Snacks"],
  ["nötter", "Snacks"],
  ["chocolate", "Snacks"],
  ["choklad", "Snacks"],
  ["candy", "Snacks"],
  ["godis", "Snacks"],
  ["crackers", "Snacks"],

  // Condiments & Sauces
  ["olive oil", "Condiments & Sauces"],
  ["olivolja", "Condiments & Sauces"],
  ["rapeseed oil", "Condiments & Sauces"],
  ["rapsolja", "Condiments & Sauces"],
  ["sunflower oil", "Condiments & Sauces"],
  ["solrosolja", "Condiments & Sauces"],
  ["balsamic vinegar", "Condiments & Sauces"],
  ["balsamvinäger", "Condiments & Sauces"],
  ["apple cider vinegar", "Condiments & Sauces"],
  ["äppelcidervinäger", "Condiments & Sauces"],
  ["white wine vinegar", "Condiments & Sauces"],
  ["vitvinsvinäger", "Condiments & Sauces"],
  ["mayonnaise", "Condiments & Sauces"],
  ["majonnäs", "Condiments & Sauces"],
  ["ketchup", "Condiments & Sauces"],
  ["mustard", "Condiments & Sauces"],
  ["senap", "Condiments & Sauces"],
  ["dijon mustard", "Condiments & Sauces"],
  ["dijonsenap", "Condiments & Sauces"],
  ["soy sauce", "Condiments & Sauces"],
  ["soja", "Condiments & Sauces"],
  ["oyster sauce", "Condiments & Sauces"],
  ["fisksås", "Condiments & Sauces"],
  ["fish sauce", "Condiments & Sauces"],
  ["sriracha", "Condiments & Sauces"],
  ["tabasco", "Condiments & Sauces"],
  ["bbq sauce", "Condiments & Sauces"],
  ["grillsås", "Condiments & Sauces"],
  ["taco sauce", "Condiments & Sauces"],
  ["tacosås", "Condiments & Sauces"],
  ["salsa", "Condiments & Sauces"],
  ["jam", "Condiments & Sauces"],
  ["sylt", "Condiments & Sauces"],
  ["marmalade", "Condiments & Sauces"],
  ["marmelad", "Condiments & Sauces"],
  ["honey", "Condiments & Sauces"],
  ["honung", "Condiments & Sauces"],
  ["maple syrup", "Condiments & Sauces"],
  ["lönnsirap", "Condiments & Sauces"],
  ["vinegar", "Condiments & Sauces"],
  ["vinäger", "Condiments & Sauces"],
  ["hot sauce", "Condiments & Sauces"],
  ["dressing", "Condiments & Sauces"],

  // Spices & Seasonings
  ["black pepper", "Spices & Seasonings"],
  ["svartpeppar", "Spices & Seasonings"],
  ["white pepper", "Spices & Seasonings"],
  ["vitpeppar", "Spices & Seasonings"],
  ["sea salt", "Spices & Seasonings"],
  ["havssalt", "Spices & Seasonings"],
  ["garlic powder", "Spices & Seasonings"],
  ["vitlökspulver", "Spices & Seasonings"],
  ["onion powder", "Spices & Seasonings"],
  ["lökpulver", "Spices & Seasonings"],
  ["paprika powder", "Spices & Seasonings"],
  ["paprikapulver", "Spices & Seasonings"],
  ["smoked paprika", "Spices & Seasonings"],
  ["rökt paprika", "Spices & Seasonings"],
  ["cayenne pepper", "Spices & Seasonings"],
  ["cayennepeppar", "Spices & Seasonings"],
  ["chili powder", "Spices & Seasonings"],
  ["chilipulver", "Spices & Seasonings"],
  ["chili flakes", "Spices & Seasonings"],
  ["cumin", "Spices & Seasonings"],
  ["spiskummin", "Spices & Seasonings"],
  ["coriander seeds", "Spices & Seasonings"],
  ["korianderfrön", "Spices & Seasonings"],
  ["turmeric", "Spices & Seasonings"],
  ["gurkmeja", "Spices & Seasonings"],
  ["cardamom", "Spices & Seasonings"],
  ["kardemumma", "Spices & Seasonings"],
  ["cinnamon", "Spices & Seasonings"],
  ["kanel", "Spices & Seasonings"],
  ["cloves", "Spices & Seasonings"],
  ["nejlika", "Spices & Seasonings"],
  ["nutmeg", "Spices & Seasonings"],
  ["muskot", "Spices & Seasonings"],
  ["ginger powder", "Spices & Seasonings"],
  ["ingefära", "Spices & Seasonings"],
  ["oregano", "Spices & Seasonings"],
  ["basil", "Spices & Seasonings"],
  ["basilika", "Spices & Seasonings"],
  ["thyme", "Spices & Seasonings"],
  ["timjan", "Spices & Seasonings"],
  ["rosemary", "Spices & Seasonings"],
  ["rosmarin", "Spices & Seasonings"],
  ["sage", "Spices & Seasonings"],
  ["salvia", "Spices & Seasonings"],
  ["tarragon", "Spices & Seasonings"],
  ["dragon", "Spices & Seasonings"],
  ["vanilla extract", "Spices & Seasonings"],
  ["vaniljextrakt", "Spices & Seasonings"],
  ["vanilla sugar", "Spices & Seasonings"],
  ["vaniljsocker", "Spices & Seasonings"],
  ["bouillon", "Spices & Seasonings"],
  ["buljong", "Spices & Seasonings"],
  ["stock cubes", "Spices & Seasonings"],
  ["salt", "Spices & Seasonings"],
  ["curry", "Spices & Seasonings"],
  ["chili", "Spices & Seasonings"],
  ["vanilla", "Spices & Seasonings"],
  ["vanilj", "Spices & Seasonings"],

  // Beverages
  ["orange juice", "Beverages"],
  ["apelsinjuice", "Beverages"],
  ["apple juice", "Beverages"],
  ["äppeljuice", "Beverages"],
  ["apple juice", "Beverages"],
  ["äppelmust", "Beverages"],
  ["sparkling water", "Beverages"],
  ["kolsyrat vatten", "Beverages"],
  ["mineral water", "Beverages"],
  ["mineralvatten", "Beverages"],
  ["tonic water", "Beverages"],
  ["energy drink", "Beverages"],
  ["energidryck", "Beverages"],
  ["coffee beans", "Beverages"],
  ["kaffebönor", "Beverages"],
  ["ground coffee", "Beverages"],
  ["bryggkaffe", "Beverages"],
  ["instant coffee", "Beverages"],
  ["snabbkaffe", "Beverages"],
  ["black tea", "Beverages"],
  ["svart te", "Beverages"],
  ["green tea", "Beverages"],
  ["grönt te", "Beverages"],
  ["herbal tea", "Beverages"],
  ["örtte", "Beverages"],
  ["hot chocolate", "Beverages"],
  ["oboy", "Beverages"],
  ["lemonade", "Beverages"],
  ["saft", "Beverages"],
  ["iced tea", "Beverages"],
  ["is-te", "Beverages"],
  ["juice", "Beverages"],
  ["coffee", "Beverages"],
  ["kaffe", "Beverages"],
  ["tea", "Beverages"],
  ["te", "Beverages"],
  ["water", "Beverages"],
  ["vatten", "Beverages"],
  ["soda", "Beverages"],
  ["läsk", "Beverages"],
  ["cola", "Beverages"],
  ["wine", "Beverages"],
  ["vin", "Beverages"],
  ["beer", "Beverages"],
  ["öl", "Beverages"],

  // Household/Cleaning
  ["dish soap", "Household/Cleaning"],
  ["diskmedel", "Household/Cleaning"],
  ["laundry detergent", "Household/Cleaning"],
  ["tvättmedel", "Household/Cleaning"],
  ["fabric softener", "Household/Cleaning"],
  ["sköljmedel", "Household/Cleaning"],
  ["surface cleaner", "Household/Cleaning"],
  ["rengöringsspray", "Household/Cleaning"],
  ["glass cleaner", "Household/Cleaning"],
  ["fönsterputs", "Household/Cleaning"],
  ["toilet cleaner", "Household/Cleaning"],
  ["toalettrent", "Household/Cleaning"],
  ["floor cleaner", "Household/Cleaning"],
  ["golvtvätt", "Household/Cleaning"],
  ["dishwasher tablets", "Household/Cleaning"],
  ["maskindiskmedel", "Household/Cleaning"],
  ["sponge", "Household/Cleaning"],
  ["disksvamp", "Household/Cleaning"],
  ["dish brush", "Household/Cleaning"],
  ["diskborste", "Household/Cleaning"],
  ["trash bag", "Household/Cleaning"],
  ["soppåse", "Household/Cleaning"],
  ["paper towel", "Household/Cleaning"],
  ["hushållspapper", "Household/Cleaning"],
  ["toilet paper", "Household/Cleaning"],
  ["toalettpapper", "Household/Cleaning"],
  ["aluminum foil", "Household/Cleaning"],
  ["aluminiumfolie", "Household/Cleaning"],
  ["plastic wrap", "Household/Cleaning"],
  ["plastfolie", "Household/Cleaning"],
  ["baking paper", "Household/Cleaning"],
  ["bakplåtspapper", "Household/Cleaning"],
  ["napkin", "Household/Cleaning"],
  ["servett", "Household/Cleaning"],
  ["candle", "Household/Cleaning"],
  ["ljus", "Household/Cleaning"],
  ["battery", "Household/Cleaning"],
  ["batteri", "Household/Cleaning"],
  ["soap", "Household/Cleaning"],
  ["tvål", "Household/Cleaning"],
  ["detergent", "Household/Cleaning"],

  // Hygiene
  ["shower gel", "Hygiene"],
  ["duschcreme", "Hygiene"],
  ["body wash", "Hygiene"],
  ["shampoo", "Hygiene"],
  ["schampo", "Hygiene"],
  ["conditioner", "Hygiene"],
  ["balsam", "Hygiene"],
  ["hand soap", "Hygiene"],
  ["handtvål", "Hygiene"],
  ["toothpaste", "Hygiene"],
  ["tandkräm", "Hygiene"],
  ["toothbrush", "Hygiene"],
  ["tandborste", "Hygiene"],
  ["dental floss", "Hygiene"],
  ["tandtråd", "Hygiene"],
  ["deodorant", "Hygiene"],
  ["perfume", "Hygiene"],
  ["parfym", "Hygiene"],
  ["razor", "Hygiene"],
  ["rakhyvel", "Hygiene"],
  ["shaving cream", "Hygiene"],
  ["raklödder", "Hygiene"],
  ["lotion", "Hygiene"],
  ["moisturizer", "Hygiene"],
  ["face wash", "Hygiene"],
  ["ansiktstvätt", "Hygiene"],
  ["sunscreen", "Hygiene"],
  ["solkräm", "Hygiene"],
  ["tampons", "Hygiene"],
  ["tamponger", "Hygiene"],
  ["pads", "Hygiene"],
  ["bindor", "Hygiene"],
  ["cotton pads", "Hygiene"],
  ["bomullsrondeller", "Hygiene"],
  ["band-aid", "Hygiene"],
  ["plåster", "Hygiene"],
]

export function lookupCategory(itemName: string): GroceryCategory | null {
  const normalized = itemName.toLowerCase().trim()

  for (const [keyword, category] of KEYWORD_MAP) {
    if (normalized.includes(keyword)) {
      return category
    }
  }

  return null
}