// Augmented entrypoint for the Supabase schema types.
//
// `database.types.ts` is auto-generated by `supabase gen types` and represents
// every jsonb column as `Json`. The app stores typed shapes (Ingredient[],
// Macros, MealType, ...) in those columns, so we narrow them here. Sync code
// imports Tables / TablesInsert / TablesUpdate / SyncableTable from this file
// instead of from database.types, which keeps end-to-end typing intact.
//
// Re-run `supabase gen types typescript --project-id udmqkraioxzcphcmlcub
// --schema public > lib/supabase/database.types.ts` after a schema change.
// The overrides below continue to apply on top.

import type { Database as Generated } from './database.types'
import type { Ingredient, Macros, MealType } from '@/lib/types'

export type { Json } from './database.types'
export type Database = Generated

type Override<T, R> = Omit<T, keyof R> & R

type RecipeOverride = {
  ingredients: Ingredient[]
  steps: string[]
  macros: Macros
  macro_mode: 'auto' | 'manual'
  tags: string[]
}

type MealPlanEntryOverride = {
  meal_type: MealType
  recipe_macros: Macros
}

type MealTypeConfigOverride = {
  enabled_types: MealType[]
}

type RowOverrides = {
  recipes: RecipeOverride
  meal_plan_entries: MealPlanEntryOverride
  meal_type_config: MealTypeConfigOverride
}

type GeneratedTables = Generated['public']['Tables']

export type Tables<T extends keyof GeneratedTables> = T extends keyof RowOverrides
  ? Override<GeneratedTables[T]['Row'], RowOverrides[T]>
  : GeneratedTables[T]['Row']

export type TablesInsert<T extends keyof GeneratedTables> = T extends keyof RowOverrides
  ? Override<GeneratedTables[T]['Insert'], Partial<RowOverrides[T]>>
  : GeneratedTables[T]['Insert']

export type TablesUpdate<T extends keyof GeneratedTables> = Partial<TablesInsert<T>>

export type SyncableTable = keyof GeneratedTables
